/* do not change this file, it is auto generated by storybook. */

import { start, updateView } from "@storybook/react-native";

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-backgrounds/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../lib/components/atoms/Button",
    files: "Button.stories.tsx",
    importPathMatcher: /^\.[\\/](?:Button\.stories\.tsx)$/,
    // @ts-ignore
    req: require.context(
      "../../lib/components/atoms/Button",
      false,
      /^\.[\\/](?:Button\.stories\.tsx)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "../lib/components/atoms/ProgressBar",
    files: "ProgressBar.stories.tsx",
    importPathMatcher: /^\.[\\/](?:ProgressBar\.stories\.tsx)$/,
    // @ts-ignore
    req: require.context(
      "../../lib/components/atoms/ProgressBar",
      false,
      /^\.[\\/](?:ProgressBar\.stories\.tsx)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "../lib/components/atoms/ProgressiveImage",
    files: "ProgressiveImage.stories.tsx",
    importPathMatcher: /^\.[\\/](?:ProgressiveImage\.stories\.tsx)$/,
    // @ts-ignore
    req: require.context(
      "../../lib/components/atoms/ProgressiveImage",
      false,
      /^\.[\\/](?:ProgressiveImage\.stories\.tsx)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "../lib/components/atoms/Skeleton",
    files: "Skeleton.stories.tsx",
    importPathMatcher: /^\.[\\/](?:Skeleton\.stories\.tsx)$/,
    // @ts-ignore
    req: require.context(
      "../../lib/components/atoms/Skeleton",
      false,
      /^\.[\\/](?:Skeleton\.stories\.tsx)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "../lib/components/atoms/Text",
    files: "Text.stories.tsx",
    importPathMatcher: /^\.[\\/](?:Text\.stories\.tsx)$/,
    // @ts-ignore
    req: require.context(
      "../../lib/components/atoms/Text",
      false,
      /^\.[\\/](?:Text\.stories\.tsx)$/
    ),
  },
];

declare global {
  var view: ReturnType<typeof start>;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require("./preview"),
  require("@storybook/react-native/dist/preview"),
  require("@storybook/addon-actions/preview"),
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view = global.view;
