import { IS_WEB } from './device';

export const COLOR_CONSTANTS = {
  MINIMUM_CONTRAST_RATIO: 2,
  DEFAULT_LIGHTNESS_ADJUSTMENT: 0.2,
  DESATURATION_LIGHTEN_AMOUNT: IS_WEB ? 0.8 : 0.2,
  DEFAULT_COLOR: '#FFFFFF',
} as const;
