name: 'Storybook to Chromatic'
on: push

# Cancel in-progress runs for pull requests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Storybook build
        uses: actions/cache@v3
        with:
          path: storybook-static
          key: storybook-static-${{ github.sha }}
          restore-keys: |
            storybook-static-

      - name: Build Storybook
        run: yarn build-storybook --stats-json

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          onlyChanged: true # Only run Chromatic on changed stories

      - name: Update Storybook URLs
        if: success()
        run: |
          STORYBOOK_URL="${{ steps.chromatic.outputs.storybookUrl }}"
          # Update docs/index.md
          sed -i.bak "s|https://.*\.chromatic\.com/|${STORYBOOK_URL}|" docs/index.md
          # Update README.md
          sed -i.bak "s|https://.*\.chromatic\.com/|${STORYBOOK_URL}|" README.md
          # Update docs/.vitepress/config.js
          sed -i.bak "s|https://.*\.chromatic\.com/|${STORYBOOK_URL}|" docs/.vitepress/config.js
          # Clean up backup files
          rm docs/index.md.bak README.md.bak docs/.vitepress/config.js.bak
