name: 'Storybook to Chromatic'
on: push

# Cancel in-progress runs for pull requests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Storybook build
        uses: actions/cache@v3
        with:
          path: storybook-static
          key: storybook-static-${{ github.sha }}
          restore-keys: |
            storybook-static-

      - name: Build Storybook
        run: yarn build-storybook --stats-json

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          onlyChanged: true # Only run Chromatic on changed stories

      - name: Update Storybook URLs
        if: success()
        env:
          STORYBOOK_URL: ${{ steps.chromatic.outputs.storybookUrl }}
        run: |
          # Use portable sed syntax for macOS and Linux compatibility
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS sed requires backup extension
            sed -i '' "s|https://[0-9a-f]\+\.chromatic\.com/|${STORYBOOK_URL}|" docs/index.md README.md docs/.vitepress/config.js
          else
            # Linux sed
            sed -i "s|https://[0-9a-f]\+\.chromatic\.com/|${STORYBOOK_URL}|" docs/index.md README.md docs/.vitepress/config.js
          fi

          # Check if files were modified
          if git diff --quiet docs/index.md README.md docs/.vitepress/config.js; then
            echo "No changes to commit"
            exit 0
          fi

          # Configure git and push changes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/index.md README.md docs/.vitepress/config.js
          git commit -m "Update Storybook URLs to latest Chromatic deployment"
          git push || {
            echo "Failed to push changes"
            exit 1
          }
